### ISSUE TITLE
feat: Toggle to have a swipe control screen size to be exclusive for the sound/brightness swipe gesture

### ISSUE THREAD

**Issue by ArcherLegend** [anddea/revanced-patches#111]
### Application

YouTube

### Feature description

Currently the swipe controls for brightness and sound can be costumised with the "swipe overlay screen size" setting and the "press-to-swipe gesture".

If possible there should be an additional setting (which should be separeted from the "swipe overlay screen size") to set a screen zone percentage to only pick up the swipe gesture for brightness or volume rather than having that area also working for the press for double playback speed / swipe horizonally to move the timeline.

### Motivation

This feature should be implemented because when using the "press-to-swipe gesture" to control sound and brightness often times the Youtube app activates the double playback speed (or scrub across the timeline depending on what you have set up in Revanced settings) and it makes using the swipe controls for audio/brightness very tedious to trigger at times.

Being able to set a separate screen percentage deadzone where the press-to-swipe gesture ONLY triggers the audio/brightness controls would completely solve the inconvenience.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [x] I have written the title and contents in English.

**Comment by anddea** [comment]
No matter what we try, the default behavior is triggered anyway. You can try to request this in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues). 

The best solution for now (I mentioned this one before somewhere) is to set the screen size for swipe to 50% (as I had before by default, and as it was in the original Vanced before ReVanced), because that way it's less buggy and does not trigger YouTube's default gestures unexpectedly.

**Comment by ArcherLegend** [comment]
Thanks for the tip, it seems to help a bit.
I'll open a request on inotia00's repo!
