### ISSUE TITLE
bug: Hide videos based on views does not work

### ISSUE THREAD

**Issue by akir45** [anddea/revanced-patches#151]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.11.38
Patches v2.223.0-dev.3

### Bug description

Does not work if YouTube's internal language is Japanese. Works fine if the internal language is English.
Videos with less than 1000 views are hidden.
![IMG_20240326_153949](https://github.com/anddea/revanced-patches/assets/91464996/a04c642f-cc24-4d4f-b6e1-28db3506054c)

### Device Environment

android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you test the latest Dev?
You have to specify multipliers in this setting submenu.

Just because YouTube shortens view count, we have to detect multipliers for each language somehow, so I decided to add custom view keys-multipliers menu to the settings, that actually pulls data from each language string. So if you translate and specify right multipliers it should work out of the box without opening this preference in the settings.

**Comment by anddea** [comment]
I just noticed there's unneeded `watching -> views`, it should be deleted in order for this setting to work. You can input you language word for views and your own multipliers.

**Comment by akir45** [comment]
It worked well. Thanks.

**Comment by anddea** [comment]
When you translate those values, there will be no need to open that menu again, because they come from strings.xml.
