### ISSUE TITLE
feat: Add a switch to old microg package after selecting "Spoof Player Parameter"

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#179]
### Application

YouTube

### Feature description

There should be a feature like that if we opt out from "Spoof Player Parameter" it switches to revanced microg package. And if we select it, it switches back to old microg.

### Motivation

It is a most useful feature for those who have issues having both OG YT and YTM alongwith RVX. As we know that we need them side-by-side. So, it will be a useful feature to use future RVX updates with old microg too.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
The only way to implement this in he right way is to add an option to select mirog vendor before patching. I opened a poll, you can vote there.

https://github.com/anddea/revanced-patches/discussions/197

I see no reason to use old microg for now, because GmsCore works the same and fixes some potential issues. It has its own issues but just like old mircog.
