### ISSUE TITLE
bug: Reddit unable to login

### ISSUE THREAD

**Issue by DaddyNix** [anddea/revanced-patches#193]
### Type

Other

### Tools used

RVX Manager

### Application

Reddit any version

### Bug description

When patching and including: change package name , you are not able to login to reddit and when excluding said patch you are able

### Device Environment

Android 14 myOS 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MorgothRB** [comment]
I changed package name and don't have this issue. 
Do you use login with your Google Account? I once had this issue (when trying to log in with my Google account, which had worked before) with patched and unpatched Reddit. After setting a password for Reddit with a browser, I was able to log in in the app again (with email and password instead of Google authentication).

**Comment by DaddyNix** [comment]
I tried both also it just says something went wrong

> I changed package name and don't have this issue. Do you use login with your Google Account? I once had this issue (when trying to log in with my Google account, which had worked before) with patched and unpatched Reddit. After setting a password for Reddit with a browser, I was able to log in in the app again (with email and password instead of Google authentication).
