### ISSUE TITLE
bug: GMSCore Micro G not registering Youtube Revanced in Cloud Messaging 

### ISSUE THREAD

**Issue by Jaydan101** [anddea/revanced-patches#199]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.11.38 

### Bug description

I am unable to receive notifications because GMS Core Micro G is not recognising the patched app. It is not registering it in cloud messaging.

Is there a solution? 
![Screenshot_20240328_151446_microG Services](https://github.com/anddea/revanced-patches/assets/152452522/03c658b0-5dba-47cc-a8af-61a5ad5fbd3d)

### Device Environment

Android 14, One UI 6.1 Samsung Galaxy S23U

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Sam101011** [comment]
Anddea hasn't released the patches that include the GMS Core switch yet. As of now, I suggest you use regular revanced or ReX, who already have.

**Comment by MorgothRB** [comment]
I had the same issue and solved it this way: 
- Export settings (YouTube -> Settings -> Revanced Extended -> Miscellaneous)
- Clear YouTube app data
- Start YouTube (it should register itself)
- Import settings

**Comment by anddea** [comment]
> Anddea hasn't released the patches that include the GMS Core switch yet. As of now, I suggest you use regular revanced or ReX, who already have.

Could you elaborate? It's implemented in [v2.223.0-dev.4](https://github.com/anddea/revanced-patches/releases/tag/v2.223.0-dev.4), it's not in stable release yet but people use dev releases anyway. I don't think the current state of GmsCore Support is stable, neither for ReVanced, nor for ReX, just because some people still say that it doesn't fix playback issues (which I don't have myself yet), but it might take several days, weeks, months to get it in the good shape.



> I had the same issue and solved it this way:

It might help. If it works with other patches by other maintainers, it should work for this one as well, if it doesn't work for all of them, then clear, reinstall GmsCore.

**Comment by zerox2** [comment]
> I had the same issue and solved it this way: 
> - _Export settings (YouTube -> Settings -> Revanced Extended -> Miscellaneous)_
> - Clear YouTube app data
> - Start YouTube (it should register itself)
> - _Import settings_
> 
> Export/Import is optional, of course

not working..microg seems being banned

**Comment by Jaydan101** [comment]
> > Anddea hasn't released the patches that include the GMS Core switch yet. As of now, I suggest you use regular revanced or ReX, who already have.
> 
> Could you elaborate? It's implemented in [v2.223.0-dev.4](https://github.com/anddea/revanced-patches/releases/tag/v2.223.0-dev.4), it's not in stable release yet but people use dev releases anyway. I don't think the current state of GmsCore Support is stable, neither for ReVanced, nor for ReX, just because some people still say that it doesn't fix playback issues (which I don't have myself yet), but it might take several days, weeks, months to get it in the good shape.
> 
> > I had the same issue and solved it this way:
> 
> It might help. If it works with other patches by other maintainers, it should work for this one as well, if it doesn't work for all of them, then clear, reinstall GmsCore.

I now see what the issue is. RVX Manager automatically pulls the Dev releases. I repatched with Vanilla Revanced Manager. All is good now. I will wait for stable release of GMS Core support. 

Thank you.

**Comment by anddea** [comment]
> I now see what the issue is. RVX Manager automatically pulls the Dev releases. I repatched with Vanilla Revanced Manager. All is good now. I will wait for stable release of GMS Core support. 

ReVanced Team and ReX published their stable releases to support GmsCore (the same one as this patches use). If something doesn't work for you (check original ReVanced and this patches), you probably have to open issue in GmsCore repo. Or maybe someone already answered how to fix this, because there are so many settings to play with, that might work for you. It might not be fixed if no one reports and we don't understand what exactly causes this issue. Everything works fine for me. 

https://github.com/ReVanced/GmsCore
