### ISSUE TITLE
suggestion: enhance time-ordered-playlist button's functionality

### ISSUE THREAD

**Issue by MondayNitro** [anddea/revanced-patches#2]
### Application

YouTube

### Suggestion description

the time ordered playlist button doesnt serve its purpose in case you begin from the latest video of a channel and want to watch videos in form of playlist. the videos are arranged from oldest to newest which means the newest video is the last video on the playlist and hence no next video is played.
i would like for it to arrange videos from newest to oldest so that im able to watch videos in series using the time-ordered-playlist button.

https://github.com/anddea/revanced-patches/assets/87489540/42db234c-e31e-4186-872a-593610f9e7f0

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
This is intentional behavior for time-ordered playlist, it is also mentioned in description of this button that it creates from oldest to newest which means the newest video will be the last in the playlist. 

For now, as a workaround, 
- You can scroll videos and start from the one you want to start (from older to newest).
- You can press the chip Oldest in Videos section of a channel, near with Latest and Popular chips. And then if you start playing first video it'll be the first in the playlist.

I had an idea to add Reverse button to the playlist sheet, near with the repeat and shuffle buttons, which will be better, because you'll be able to reverse any playlist, not only related to time-ordered playlist button. But currently I have no idea how to implement it and have not much time to investigate. It's much easier to implement it on the website than in the app.

Maybe @YT-Advanced could help with the playlist reordering.
