### ISSUE TITLE
suggestion: My version of the icons for the patch `Shorts overlay buttons` `Tiktok`

### ISSUE THREAD

**Issue by odkate** [anddea/revanced-patches#223]
### Application

YouTube

### Suggestion description

I kept the transparency and gradient of the icons and made them the same size as the original YouTube ones.
![Screenshot_20240330-213044](https://github.com/anddea/revanced-patches/assets/90364108/c2db182d-648a-4769-bb1e-bbfd54fcc7c9)

[tt.zip](https://github.com/anddea/revanced-patches/files/14813158/tt.zip)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Thank you. I added them. 

All on_32c images are used in old versions of YouTube. And they are a little misaligned on purpose just to match XML icons, you can see example in Outline folder; for old versions of YouTube, there are XML files and just 3 images, I added icons but didn't implement the code for those 2 images just because it will be inconsistent with XML icons. For new versions of YouTube it should be fine. 

Also, there's no on_32c images in xxxhdpi. Please verify if everything's good.

**Comment by odkate** [comment]
> Also, there's no on_32c images in xxxhdpi

Because they are not in the original for this dpi either



> on_32c

In the original they come with the same resolution, the size is the same as on_shadowed, but I just made a copy of on_shadowed

**Comment by odkate** [comment]
> XML files

I converted it to xml format, but 96x96(drawable-xxhdpi), because 32x32 is very distorted when converting the image
[drawable.zip](https://github.com/anddea/revanced-patches/files/14817052/drawable.zip)

I tried it on my phone, it works fine

**Comment by anddea** [comment]
I added them. You can test them either in old versions of YouTube or spoof to old version in Misc.

If you can, try to minimize the SVG path in XML files, make them one line like in Outline icons. Though it'll be hard, because they weren't vector icons from the beginning.
If you have more ideas for fixing/refining or adding new icons anywhere, you can send me or open a Pull Request, whatever suits you the best.
