### ISSUE TITLE
feat(YouTube - Swipe Controls): Save and restore brightness

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#288]
### Application

YouTube

### Feature description

'Save and restore brightness' switch...

This was a setting that was in a RVX old version, and for some reason it was deleted.

This is a ReVanced setting now.

### Motivation

:)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
This option is removed probably because we have auto-brightness switch, you can swipe down at any moment and it will reset the brightness. And there's a new Pull Request in ReVanced repo that does the same by removing switch for save and restore brightness but adding auto-brightness switch. So how this feature is important? Do we really need additional switch when we have more advanced way to reset brightness whenever we want by swiping down without leaving the player and going through settings just to find one switch?

**Comment by zerozero0022** [comment]
I just want to reset to the app default brightness automatically when i open the player again and play the video, after use the swipe control to adjust the brightness rules and watch the video.

**Comment by anddea** [comment]
It will reset brightness every time you play a new video.
