### ISSUE TITLE
suggestion(YouTube): revert to old default video quality logic

### ISSUE THREAD

**Issue by shreyjain1998** [anddea/revanced-patches#388]
### Application

YouTube

### Suggestion description

Can you revert commit [1ee2743](https://github.com/anddea/revanced-patches/commit/1ee2743c452795dba4c7a52a7779e35568fe3e6a)? 

I feel like `Default Video Quality` setting was way stable earlier than it is now. Most of times video continues to play on 360p even though 2160p is set. Some times video keeps playing on 720p or 1080p when 2160p quality is available. Also, it takes more than 10 seconds to switch to higher quality. I have tested ReVanced and it's happening there too.

So I believe you should revert the changes as the previous logic was working very well.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I'm thinking about this for multiple reasons but your reason is the least important actually. Because quality is not applied immediately, it loads a little bit of the video in lower quality anyway (both with old and new logic), what you've seen in the UI is kind of a lie, it showed the quality that have been set already (as default) but was applied only when passed the buffered portion of the video. Now it shows you the actual quality for the playing segment. Other than that it's the same. 

The old method is good if you want to know the default quality, but it doesn't mean that the video is actually playing in that quality.

**Comment by Francesco146** [comment]
does anyone actually want to know at which quality **a segment** is reproduced? the buffer stays for a couples of seconds, not sure anyone will notice a difference

**Comment by shreyjain1998** [comment]
No, actually this issue is not only for preloaded buffer but for major segment of the video. It won't switch to 2160p even if I keep on playing it till 1 or 2 minutes (pics below). Similarly, it will keep on playing 360p/480p for 1080p quality videos. I was not facing this issue before v2.224.0-dev.10 release though.

![Screenshot_2024-04-28-09-12-13-141_anddea youtube](https://github.com/anddea/revanced-patches/assets/107779107/469d2a7b-256d-4a7c-b989-b74c2704f299)
![IMG_20240428_091734](https://github.com/anddea/revanced-patches/assets/107779107/147be61f-562b-43f5-851e-b347f88e094f)
![IMG_20240428_091653](https://github.com/anddea/revanced-patches/assets/107779107/9658432a-7e67-4022-8199-c479dd3f2ac1)

**Comment by shreyjain1998** [comment]
v2.224.1-dev.4 working flawlessly, thank you @anddea
