### ISSUE TITLE
Find some options

### ISSUE THREAD

**Issue by speedlorenzo12** [anddea/revanced-patches#422]
### Application

YouTube

### Question description

Hi, where are the options in YT settings these patches? If they aren't there I'll probably create a feature request(all patch whit toggle option and i dont probably find all patch ):
Hide voice search button
Hide animated button background
Force snackbar theme
Force hide player button background 
Force hide fullscreen button
Force Hide collapse button
Force disable short dim 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
They are all forcible patches, but they work better than toggle settings. For example there's an option to hide collapse button but still we had to implement this forcible patch (force hide collapse button), because it works without issues unlike the one with the toggle. 

There will be some of them implemented with toggles but some of them won't be implemented, at least for now, as they're buggy and will ruin user experience.
