### ISSUE TITLE
bug: Playlists at library disappears

### ISSUE THREAD

**Issue by Spaceshiprace** [anddea/revanced-patches#437]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT 19.05.36

### Bug description
![Screenshot_2024-05-07-23-40-38-857_anddea youtube_1](https://github.com/anddea/revanced-patches/assets/156727749/e448f49a-75aa-4483-b0b4-a2d8188f2531)

### Error logs

```shell
idk
```

### Solution

Idk honestly

### Additional context

question : why anddea patches are very unstable unlike ReX

### Device Environment

Android

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
What playlists disappear and why? I cannot reproduce it. 

What is unstable for you?

**Comment by anddea** [comment]
Export and send me your settings.

**Comment by Francesco146** [comment]
try pulling up the refresh button in You Library.

**Comment by anddea** [comment]
I'm not sure what's the cause here. Try to clean install the app and then just import your settings. Let me know if it changed anything. 

The issue is not reproducible on my side even with your settings. Are you using default patch selection in your patching tool? Send me your selected patches. 

Things can get broken sometimes because of some side factors, e.g. rom filters, adblock, they're just examples but I see no possible way how can those could impact playlists even if you use such things. 

P.S. This is a misconception that there are no bugs in ReX. There are bugs everywhere actually, in original YouTube, original ReVanced, RVX and ReX. Your first mentioned issue was because of the patch that doesn't exist in RVX or ReX. It exists in original ReVanced though, and they still didn't fix it and this bug was caused by another feature, it was just side effect of that feature (big companies would've told you it's a feature, not a bug). You're doing a great job by letting us know about those bugs so we can fix them, we cannot know about every bug until someone reports. But this issue cannot be reproduced, not by me, not by Francesco and probably no one else if no one has commented, so should be something on your side.

**Comment by anddea** [comment]
Let me know what other bugs you face
