### ISSUE TITLE
question: Custom Translation File

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#465]
### Application

YouTube

### Question description

If I apply custom translation patch to yt app, will I not be able to use it except for English and custom translation language?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It will only apply to Extended settings. All other interface languages from original app will remain. When adding custom translation you won't see English too, because this custom translation will replace main file which is English and won't add other translations. 

In the note for release I left a message that I can try to make an option to apply custom translation only to a specific language. Do you need that?

**Comment by zerozero0022** [comment]
I know it only applies to extended settings.

You're saying that file B, not file A, will be replaced, right?

A - src/main/resources/youtube/translations/ko-rKR/strings.xml
B - src/main/resources/youtube/settings/host/values/strings.xml
