### ISSUE TITLE
suggestion: About Translation

### ISSUE THREAD

**Issue by akir45** [anddea/revanced-patches#489]
### Application

YouTube

### Suggestion description

When applying inotia crowdin strings from a custom language file, some of the string names are different and will not be translated.
![Screenshot_2024-05-18-14-48-00-564_anddea youtube](https://github.com/anddea/revanced-patches/assets/91464996/8855d1ca-8d55-4ad5-946f-f090c607427d)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I know, but automated script cannot detect the translation and therefore it cannot understand if already translated strings are replaced with old untranslated. That's why I recommended to contribute there, once inotia accepts them to his repository, it'll be here as well. 

For now, I can revert translation for Japanese that was sent here as Pull Request, but if inotia adds translation with untranslated strings then it will replace here as well automatically.
