### ISSUE TITLE
Old seekbar thumbnail 

### ISSUE THREAD

**Issue by MoniBlackouts** [anddea/revanced-patches#529]
### Type

Other

### Tools used

Revancify

### Application

Youtube 19.19.39 and 19.20.34

### Bug description

When patching it throws me a warning "Restore old seekbar thumbnail setting is not supported in this version" patched sucessfuly and usable but old seekbar thumbnail not there otherwise OK .. Tried both versions.. Same problem in inotia latest patch too

### Device Environment

Android 12, One UI 4.1.. Rooted official firmware 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Yes, it is also mentioned in inotia's patches that `Restore old seekbar thumbnails` setting has been deprecated in YouTube `v19.17.41` and later. No solution for now, maybe one day there will be a solution for that. Since there's nothing new on YouTube itself after 19.16, you can still patch it with latest patches and it will work just fine.

**Comment by MoniBlackouts** [comment]
> Yes, it is also mentioned in inotia's patches that `Restore old seekbar thumbnails` setting has been deprecated in YouTube `v19.17.41` and later. No solution for now, maybe one day there will be a solution for that. Since there's nothing new in YouTube itself after 19.16, you can still patch it with latest patches and it will work just fine. 

Yes bro.. No problem btw it's not a big deal. Thanks
