### ISSUE TITLE
Give a option to apply visual preference icon only for YouTube & ReVanced Extended main setting menu

### ISSUE THREAD

**Issue by NichirinSword** [anddea/revanced-patches#576]
### Application

YouTube

### Suggestion description

Option to exclude visual preference icon patch for ReVanced Extended submenu.
I kinda find it mess as some submenu has it and some not.
If this patch only applies to YouTube & ReVanced Extended main setting menu, It would look much cleaner.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
There was an option to turn on main, RVX and submenu icons before but I removed it since it's unnecessary complex and hard to maintain. So I'm not planning to do that. 

You can suggest your icons for remaining settings if you want. 
https://github.com/anddea/revanced-patches/discussions/567

> I kinda find it mess as some submenu has it and some not.

Why is that? Is it a mess for your Android settings? Although I don't know your ROM, AOSP, and other ROMs based on it have the same thing: some settings have icons, while others do not. Same for other apps.
