### ISSUE TITLE
question: Microg related

### ISSUE THREAD

**Issue by gigachaand** [anddea/revanced-patches#651]
### Application

YouTube

### Question description

I want to use a different Microg other than recommended one..but can't do it.
Rvx YouTube not detecting it... Can u do something about it..?? Plz

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by gigachaand** [comment]
In ReVanced there is option to change Microg package value.. 
![Screenshot_2024-06-25-17-08-05-289_app revanced manager flutter-edit](https://github.com/anddea/revanced-patches/assets/96541364/8006f679-0d7e-4057-b387-33e3394f191a)
![Screenshot_2024-06-25-17-08-49-079_app revanced manager flutter-edit](https://github.com/anddea/revanced-patches/assets/96541364/fc0953d3-ca14-4f38-aabf-d92b7d650651)

**Comment by anddea** [comment]
Previously, I conducted a poll regarding keeping the old microG alongside the new one. Most people considered it unnecessary.

The previous microG had different backend code, which might be incompatible. Did you test it? Did it work with the old one? If yes, then reopen this in inotia's repo.

Due to the unwillingness of other contributors and maintainers to consider reintegrating the old microG integration, its implementation in this project could significantly diverge, making it unfeasible to continue this project at some point in the future. There are two possible solutions: either persuade other project members or accept the situation.

The current microG is safer in many respects, and maybe no one will consider maintaining or reintegrating the old one.
