### ISSUE TITLE
question: Wondering why this repos exists

### ISSUE THREAD

**Issue by hyperssmp** [anddea/revanced-patches#750]
### Application

Other

### Question description

1. Why did you create this repos when all the features come from inotia or from contributors ? Additational, from what I see, the new features are all about theme. And you can't even add an on/off switch for your patches.
3. You do not and have never given credit in your commits. That just proves that you're an ungrateful person.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Commits made in this repo via PRs always credit every contributor, including translations. This differs from Inotia's repo, where those contributors cannot be seen.

Commits that I make myself, using files or ideas provided by others, include those authors as co-authors. However, I encourage people to open PRs and fix potential issues so that I am not listed as a co-author at all.

Commits merged from other repos are made by an automated script, tested, and pushed after some time. Because of this automation, they don't always show authors. If someone is concerned with it, they can improve automation flow or contribute directly here. Some commits from Inotia originate from the ReVanced Team and me without explicitly mentioning the real authors as well. Git primarily reveals the source code rather than the true contributors. Upon closer inspection, even larger projects may not always credit all authors. Besides maintaining this repository, I actively support and encourage other contributors in their contributions to this project (including RV and RVX). 

If you have the time to ask these questions, you probably have the time to delve deeper, read PRs, comments, issues, and discussions. You'll understand why things are the way they are and why your assumptions may be incorrect.

If you believe nothing new has been introduced, you might be surprised to learn how many innovations have originated here and moved to other repos. And there are more innovations to come; some features are still unique here. 

If patches lack toggles in settings, they may be unstable, detrimental to performance, or lacking a better solution. It's incorrect to assume there are no unique options with toggles; in fact, more than half of them are internal options. 

Patches like theming are genuinely challenging, and I believe everyone should respect those contributors (all of whom are mentioned). Crafting a single icon can require significantly more time and effort than creating ten functional patches.

I keep this repo open because it offers distinct features and a slightly different structure that may be more suitable for some people, especially for non-English-speaking users of these apps.

You are free not to use it if you prefer. However, questions about its use are better directed at other users who find it beneficial. It would be more helpful for you to understand why other people are using it, rather than why I maintain it.

**Comment by hyperssmp** [comment]
> Some commits from Inotia originate from the ReVanced Team and me without explicitly mentioning the real authors as well. Git primarily reveals the source code rather than the true contributors.

It is just "some" of them, but you NEVER credit to the author. If it's like you say, then if someone else do illegal works you can do the same thing ?

> If you believe nothing new has been introduced, you might be surprised to learn how many innovations have originated here and moved to other repos. And there are more innovations to come; some features are still unique here.

All I found out is is just a search bar and reorder the settings. Whitelist is from ReX, and others things is just changing icon, etc

> If patches lack toggles in settings, they may be unstable, detrimental to performance, or lacking a better solution. It's incorrect to assume there are no unique options with toggles; in fact, more than half of them are internal options.

Previously your repos also had the feature to hide the fullscreen button. Obviously that patch doesn't have a toggle, but currently in inotia's version it does. So is it because you don't have the skills to find "a better solution", or is it because what inotia did is "unstable, detrimental to performance" ?

> Crafting a single icon can require significantly more time and effort than creating ten functional patches.

This is definitely unreasonable. I see a few other contributors who can create and edit icons. Meanwhile, how many people can make functional patches? Apparently right now I see only Osumatrix, LisoUseInAIKyrios, inotia00 and YT Advanced guys. If you still want to prove me wrong, pick a feature request from your repos and make it.

**Comment by anddea** [comment]
@hyperssmp I think you're the only one disrespectful here. Not only you called other contributors who try to learn and do things for this project useless, but you also waste the time of those you do respect. If you're capable of creating these things that anyone can create, why haven't you done so?

We all have different skills; we excel in some areas and struggle in others. Are you suggesting you were born knowing everything?

**Comment by anddea** [comment]
> force hide the fullscreen button

Yes, the solution was unknown, and previous iterations were buggy; even now, it occasionally bugs out. The same applies to hiding elements in settings and other patches. All (or almost all) forced patches will be more performant. Until we find a better solution, appreciate the patches you have, even if you dislike their type or choose not to use them.

> All I found out is is just a search bar, reorder the settings, add some icons

You're overlooking other unique features.

Open your eyes, and you'll see contributors, except those that are automated. Go read through issues and discussions, where I spend time explaining how to do things, rather than wasting our time. I never belittle others like you do.

**Comment by hyperssmp** [comment]
@anddea I done my patches, now is your turn 😏

**Comment by Francesco146** [comment]
do you realize that you are so childish? people like you are the evil of open source projects. you make new developers that want to join the team go away. one is trying to learn something but if you don't produce much results then your work is worth nothing. what a bad way to live, congratulations on your new patches.

I just hope you rethink what you wants to be in this community and in the world as well.

**Comment by anddea** [comment]
@hyperssmp this one is easy actually, it's just replicates existing patch, but good for you. You're now more helpful for someone who needs this feature, the only downside is this worthless waste of time of so many people.

**Comment by YT-Advanced** [comment]
> @hyperssmp this one is easy actually, it's just replicates existing patch, but good for you. You're now more helpful for someone who needs this feature, the only downside is this worthless waste of time of so many people.

If it's that simple then why don't you do it haha

**Comment by anddea** [comment]
Lol, I knew it was your second account @YT-Advanced. To answer your question, because I have no time. That doesn't mean other contributors can't open PRs here.

**Comment by YT-Advanced** [comment]
Maybe he's a bit angry, but I think from my current perspective I partly agree with him 🫠

**Comment by anddea** [comment]
With him, you mean him or me? 

There are a lot of issues that I come across in months just to realize that it was a 5 minute deal. You guys definitely don't know what busy means.

**Comment by YT-Advanced** [comment]
> @YT-Advanced With him, you mean him or me?

I mean with him

**Comment by YT-Advanced** [comment]
> > There are a lot of issues that I come across in months just to realize that it was a 5 minute deal. You guys definitely don't know what busy means.
> 
> So why keeping this repos if u can't maintain it

nah there are many features that can't be included in rvx right away, so you can consider this repos a testing ground for new features

**Comment by hyperssmp** [comment]
> nah there are many features that can't be included in rvx right away, so you can consider this repos a testing ground for new features

for example ?

**Comment by anddea** [comment]
> I mean with him

Then craft a good icon, we'll see. I'm not saying this because of myself, as I haven't been working on icons recently, as you can see. And I definitely don't care if someone doesn't like what I do. However, you should know that some contributors spent days creating their icons. This patch simply copied a similar existing patch in 5 minutes. How can you argue that? I seriously doubt if you truly understand how challenging that work can be. Understanding bytecode takes time, for sure, but this patch was straightforward. Nonetheless, he did a commendable job by doing something that neither I nor others like you or inotia did, and doesn't matter why, because we have no time or for any other reasons. So, should he also contend with you saying that you don't create great things?

**Comment by anddea** [comment]
@hyperssmp I wish you a bright future filled with features that surpass all of ours, but that shouldn't make you feel entitled to belittle others. Otherwise, no one will use your contributions. Supporting, teaching, and helping other contributors—what I'm doing here and what other maintainers do—comes at a great cost; it's priceless. It's unfortunate that you don't understand this. You didn't mention many contributors from the past and present who have done outstanding work that no one else could match.

**Comment by YT-Advanced** [comment]
@anddea okay, calm down. Here, I need to clarify a few things:
1. First of all, I partly agree with him, not completely.
2. The patches he created are incredibly simple, BUT to understand it is quite difficult.
3. Making icons can be time-consuming, but when you say it's harder than 10 feature patches, I disagree. Why ? First of all, if you know Big O, you probably also know about algorithms. Most coding algorithms are easy, what's difficult is how you come up with the idea. The same thing happens with patches. YouTube is closed source, all code is obfuscated. This means you have to dig through about 120MB of code to find the exact hook location. If I assigned you to make a "very simple" patch to make the margins of the action buttons balanced, would you be able to do it in 1 year? As for icons, at most I only need about 1 week to create 1 icon, so in 1 year I can create about 52 such icons. So which one do you think is more difficult?

**Comment by YT-Advanced** [comment]
you can ask @Francesco146 (who just meeting with bytecode some recent day) to understand 😭

**Comment by YT-Advanced** [comment]
> So why did you create second account, YT-Advanced?

Huh, looks like we have some misunderstandings here

**Comment by hyperssmp** [comment]
@YT-Advanced You haven't answer my question yet
https://github.com/anddea/revanced-patches/issues/750#issuecomment-2250692104

**Comment by YT-Advanced** [comment]
> @YT-Advanced You haven't answer my question yet [#750 (comment)](https://github.com/anddea/revanced-patches/issues/750#issuecomment-2250692104)

Huh, my obligation ?

**Comment by anddea** [comment]
Don't worry, I'm actually calm. It was obviously an exaggeration about the 10 patches. Although if we're talking about patches like this one, sure, you could create 50 similar patches and it would be easier than creating one icon. But why are you so triggered?

**Comment by YT-Advanced** [comment]
> Don't worry, I'm actually calm. It was obviously an exaggeration about the 10 patches. Although if we're talking about patches like this one, sure, you could create 50 similar patches and it would be easier than creating one icon. But why are you so triggered?

Uhm I'm still not sure where I got triggered bruh. I'm just trying to explain my point of view

**Comment by hyperssmp** [comment]
> Huh, my obligation ?

You say it without proving it to me

**Comment by YT-Advanced** [comment]
Okay, I think we should stop here

> but looks like you a little though.

@anddea I don't know why you think this guys is me, maybe we can talk a little in telegram

> You say it without proving it to me

As I said, my obligation?

**Comment by YT-Advanced** [comment]
@hyperssmp Here you [are](https://github.com/anddea/revanced-patches/pull/684), so can we stop now?
