### ISSUE TITLE
feat(YouTube - Keyword Filter): Hide Videos From Related Videos With Keywords Setting

### ISSUE THREAD

**Issue by harry-osborn1** [anddea/revanced-patches#790]
### Application

YouTube

### Feature description

This request is about adding a feature/setting *"Hide videos from related videos with keywords"*.

Basically **I always wanted to hide videos from related videos with keywords** while watching any video. Then **someone told me that "Turn on the Hide Videos From Home** setting It'll hide videos from related videos" 
I did it and yes it worked.
**But** after using this setting for some days I found out that this setting also hides videos from "channel's videos tab"(basically channel's home) too.

So the **main problem is** "Hide videos from home" also hides videos from both places which I think is a problem for most people.

So it is **really necessary** to add a new setting called
 "Hide videos from related videos with keywords"
and make "Hide vid from home" to only hide videos from channel home, not from related videos.

     <<<[Channel Home Tab]:>>>

     

![Screenshot_20240807-183943](https://github.com/user-attachments/assets/f6699567-3b0f-4fc3-8998-1efe48d11b11)

     <<<[Revanced Settings]:>>>
         

![Screenshot_20240807-175610](https://github.com/user-attachments/assets/67ce4729-9c1d-4c4d-b7db-7d8e3be6afb7)

### Motivation

Because one setting works in two places, so it creates problem for me and others. 

After adding these new features, people will be able to choose whether they want to hide videos from channel's home or not.

I hope you'll implement this soon. Thanks brothers!

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I can separate related videos under the player from the home tab/feed, but videos in the channel profile will be hidden anyway. The keyword filtering hides based on the current active tab. For example, if you open a channel from the home tab, the filtering will see that the home tab is still active and will hide the videos because of that. Currently, the player window, home tab, and unknown tabs are considered as the home tab, so it will filter all of them with just one toggle.

If I separate the home tab and related videos: 
1. If you **enable filtering in the home tab** and open a channel profile from any other tab - channel videos won't be filtered. If you open a channel profile from the home tab, the videos from the channel will be hidden. 
2. If you **enable filtering of related videos under the player** and click the channel name under the player - it will hide the videos on the channel briefly until you scroll back and forth. This is because when you click the channel from the player view, it is considered a player window at the moment, but when you scroll back and forth, it will notice that the player window is actually minimized and will return the filtered videos. If you open a channel from search or the home feed, or any other tabs by clicking on the channel image in the feed, it won't filter it at all. Also note, that if you enable filtering in other tabs, for example, home feed and then open channel from player view but home tab is active, it will filter videos from channel anyway.

This current logic cannot be improved as no better solution has been found by anyone, not just me.

So, do you still think that related videos under the player should be separated?

**Comment by harry-osborn1** [comment]
Sorry for replying too late(Github didn't show notification of your comment or I'm new to github so don't know many things)

I think you should separate them somehow it'll be helpful.
