### ISSUE TITLE
Move SponsorBlock popin window to the left ?

### ISSUE THREAD

**Issue by smed79** [anddea/revanced-patches#832]
### Application

YouTube

### Question description

Hi 👋 

SponsorBlock popin to create new segment has been switched from left to right in resent update without any known raison. This is very annoying especially when you use this feature a lot I was hoping that this window would open in a specific place. Also, as is known, there are icons on the right below the videoplayer, and I started clicking on them by mistake when trying to click SB icons, especially on a small screen.

Is there a way through the settings for example to open this window in its original place on the left, below the video player on the left?

- `https://i.imgur.com/QkXtBtS.png`

Thank you.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Cannot see the image. Can you upload it here?

**Comment by anddea** [comment]
I made it draggable. Needs more testing though, didn't have much time to polish it. Give your feedback. New segment window position will reset every time you restart the app.

**Comment by anddea** [comment]
I’ll try to add a patch option to select the default alignment in the future.

Dragging interferes with interface gestures only in portrait mode (at least for me). In landscape mode, it might interfere with swipe gestures for brightness and volume, mostly because of the small handle and the numerous additionally injected swipe gestures. However, if you tap the screen to show controls, you can drag it without issues. Dragging is calculated in pixels, not percentages, so if you drag in landscape mode to the far left, you might not see the new segment window in portrait mode unless you drag it back or reopen the app.

The buttons I use most in this new segment window are the rewind and forward buttons. I use them not only for creating segments but also for rewinding to specific points in a video that I want to examine more closely. Therefore, I find it very difficult to reach the rewind or forward buttons when they’re on the left side, as they are right at the edge. That’s why I made this window default to the right side. 

I understand your concern about missing and clicking the wrong buttons, like the overlay buttons. It’s probably the same issue with dragging the new segment window.

**Comment by smed79** [comment]
> I’ll try to add a patch option to select the default alignment in the future.

That will be very helpful to manually set depending our preference 👍

> The buttons I use most in this new segment window are the rewind and forward buttons.

Same thing as me 👍

Again thanks for the good work 🔨

**Comment by anddea** [comment]
Added patch option in the latest release.

**Comment by smed79** [comment]
> Added patch option in the latest release.

Worked as expected 👍
Thanks for your responsiveness.

> Dragging is calculated in pixels, not percentages, so if you drag in landscape mode to the far left, you might not see the new segment window in portrait mode unless you drag it back or reopen the app.

Is it planned to convert the calculation to percentages or is it difficult/impossible 👀 ?

_It's not a request, it's a simple question_ ☝️

**Comment by anddea** [comment]
Didn't think about that yet. Maybe one day.
