### ISSUE TITLE
YouTube earbud controls

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#842]
### Application

YouTube

### Feature description

Can we get earbud skip/rewind controls in YouTube and YouTube Music? Right now if you double tap on an earbud it'll skip to the next video or song.

### Motivation

It's convenient

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MtndaleRedneck** [comment]
Still not doable?

**Comment by anddea** [comment]
> Still not doable?

Earbuds send hardware media events directly to the OS media session layer. Consequently, remapping or disabling these gestures globally is a function of the system software or the manufacturer's companion app. If you want to disable this gesture across multiple apps, using the earbuds' official companion app to turn off or modify the gesture is the best approach.

While we can theoretically (key word here - theoretically) intercept and disable this behavior within our patches by injecting Smali instructions into the media callback methods before release, it is uncertain if the effort is worthwhile. Depending on how the playback engine handles these overrides, this patch may or may not break other expected media events, such as the next button inside the system notification player, the lock screen, connected smartwatches, etc. That's why it's not doable and will never be.
