### ISSUE TITLE
bug: Can't change Reddit package name

### ISSUE THREAD

**Issue by Ketsuyumi** [anddea/revanced-patches#908]
### Type

Error while patching

### Tools used

CLI

### Application

Reddit v.2024.17.0

### Bug description

 java -jar revanced-cli.jar patch -p patches.rvp --ei 43 -OpackageName="com.reddit.revanced" Reddit.apk

![image](https://github.com/user-attachments/assets/e8f67ed0-dcc8-4a5d-af73-ec715f9a7bc4)

### Device Environment

Windows 11 Pro

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
The key to change the package name is `packageNameReddit`
 https://github.com/anddea/revanced-patches/blob/4cf965eaa292cbe660e379aa38f8c09581df8fb6/patches/src/main/kotlin/app/revanced/patches/reddit/layout/branding/packagename/ChangePackageNamePatch.kt#L26

So you need to use
```bash
-OpackageNameReddit=....
```

You receive this error, because when you enable the patch it uses original package name by default.
